server:
  port: 8000
  servlet:
    context-path: /yuexiang
  #最大工作线程数，默认200, 4核8g内存，线程数经验值800
  #操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。
  tomcat:
    max-threads: 1000
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 100
spring:
  application:
    name: producer
  main:
    allow-bean-definition-overriding: true
    #http编码设置
    http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 192.168.20.242:9876
      bindings:
        output:
          destination: queue_test_topic
          content-type: application/json