server:
  port: 8100
#  servlet:
#    context-path: /
  #最大工作线程数，默认200, 4核8g内存，线程数经验值800
  #操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。
  tomcat:
    max-threads: 1000
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    min-spare-threads: 100
  undertow:
    url-charset: UTF-8
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 8
    max-headers: -1
    max-http-post-size: -1
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
spring:
  application:
    name: server
  main:
    allow-bean-definition-overriding: true
    #http编码设置
    http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  cache:
    type: redis
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: dubboredis
    # Redis数据库索引（默认为0）
    database: 3
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      ## 连接池名称
      pool-name: HikariPool
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      connection-test-query: SELECT 1
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 最小空闲连接数量
      minimum-idle: 5
  aop:
    auto: false
    proxy-target-class: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml

debug:
  false
logging:
  level:
    com:
      enjoy: debug